######################################################################
##
## Filename: bullet_ctrl.udo
## Created on: Sat Jun 04 13:54:51 Europe de l’Ouest (heure d’été) 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
