######################################################################
##
## Filename: player0.udo
## Created on: Sun May 15 17:52:41 Europe de l’Ouest (heure d’été) 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
